/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.formatting2;

import arduinoML.App;
import arduinoML.Brick;
import com.google.inject.Inject;
import com.polytech.unice.borduino.concretesyntax.services.BorduinoGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class BorduinoFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private BorduinoGrammarAccess _borduinoGrammarAccess;
  
  protected void _format(final App app, @Extension final IFormattableDocument document) {
    EList<Brick> _bricks = app.getBricks();
    for (final Brick brick : _bricks) {
      document.<Brick>format(brick);
    }
  }
  
  public void format(final Object app, final IFormattableDocument document) {
    if (app instanceof XtextResource) {
      _format((XtextResource)app, document);
      return;
    } else if (app instanceof App) {
      _format((App)app, document);
      return;
    } else if (app instanceof EObject) {
      _format((EObject)app, document);
      return;
    } else if (app == null) {
      _format((Void)null, document);
      return;
    } else if (app != null) {
      _format(app, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(app, document).toString());
    }
  }
}
