/*
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.ide


/**
 * Use this class to register ide components.
 */
class BorduinoIdeModule extends AbstractBorduinoIdeModule {
}
