/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.ide;

import fr.unice.polytech.si5.dsl.rhythm.ide.AbstractRhythmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RhythmIdeModule extends AbstractRhythmIdeModule {
}
