/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.ui;

import com.google.inject.Injector;
import fr.unice.polytech.si5.dsl.rhythm.ui.internal.RhythmActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RhythmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RhythmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RhythmActivator activator = RhythmActivator.getInstance();
		return activator != null ? activator.getInjector(RhythmActivator.FR_UNICE_POLYTECH_SI5_DSL_RHYTHM_RHYTHM) : null;
	}

}
