/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax;

import com.polytech.unice.borduino.concretesyntax.BorduinoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BorduinoStandaloneSetup extends BorduinoStandaloneSetupGenerated {
  public static void doSetup() {
    new BorduinoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
