/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax;

import com.polytech.unice.borduino.concretesyntax.AbstractBorduinoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BorduinoRuntimeModule extends AbstractBorduinoRuntimeModule {
}
