/*
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.serializer;

import arduinoML.Actuator;
import arduinoML.App;
import arduinoML.ArduinoMLPackage;
import arduinoML.Condition;
import arduinoML.DigitalSignal;
import arduinoML.KeyboardSensor;
import arduinoML.LCDScreenActuator;
import arduinoML.Sensor;
import arduinoML.State;
import arduinoML.StringSignal;
import arduinoML.Transition;
import com.google.inject.Inject;
import com.polytech.unice.borduino.concretesyntax.services.BorduinoGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BorduinoSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BorduinoGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ArduinoMLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ArduinoMLPackage.ACTION:
				sequence_Action(context, (arduinoML.Action) semanticObject); 
				return; 
			case ArduinoMLPackage.ACTUATOR:
				if (rule == grammarAccess.getActuatorRule()) {
					sequence_Actuator(context, (Actuator) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getBrickRule()) {
					sequence_Actuator_Brick(context, (Actuator) semanticObject); 
					return; 
				}
				else break;
			case ArduinoMLPackage.APP:
				sequence_App(context, (App) semanticObject); 
				return; 
			case ArduinoMLPackage.CONDITION:
				if (rule == grammarAccess.getConditionRule()) {
					sequence_Condition(context, (Condition) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getInitialConditionRule()) {
					sequence_InitialCondition(context, (Condition) semanticObject); 
					return; 
				}
				else break;
			case ArduinoMLPackage.DIGITAL_SIGNAL:
				sequence_DigitalSignal(context, (DigitalSignal) semanticObject); 
				return; 
			case ArduinoMLPackage.KEYBOARD_SENSOR:
				if (rule == grammarAccess.getBrickRule()) {
					sequence_Brick_KeyboardSensor(context, (KeyboardSensor) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getKeyboardSensorRule()) {
					sequence_KeyboardSensor(context, (KeyboardSensor) semanticObject); 
					return; 
				}
				else break;
			case ArduinoMLPackage.LCD_SCREEN_ACTUATOR:
				if (rule == grammarAccess.getBrickRule()) {
					sequence_Brick_LCDScreenActuator(context, (LCDScreenActuator) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLCDScreenActuatorRule()) {
					sequence_LCDScreenActuator(context, (LCDScreenActuator) semanticObject); 
					return; 
				}
				else break;
			case ArduinoMLPackage.SENSOR:
				if (rule == grammarAccess.getBrickRule()) {
					sequence_Brick_Sensor(context, (Sensor) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getSensorRule()) {
					sequence_Sensor(context, (Sensor) semanticObject); 
					return; 
				}
				else break;
			case ArduinoMLPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case ArduinoMLPackage.STRING_SIGNAL:
				sequence_StringSignal(context, (StringSignal) semanticObject); 
				return; 
			case ArduinoMLPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (actuator=[Actuator|EString] value=Signal)
	 */
	protected void sequence_Action(ISerializationContext context, arduinoML.Action semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.ACTION__ACTUATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.ACTION__ACTUATOR));
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.ACTION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.ACTION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getActionAccess().getActuatorActuatorEStringParserRuleCall_0_0_1(), semanticObject.eGet(ArduinoMLPackage.Literals.ACTION__ACTUATOR, false));
		feeder.accept(grammarAccess.getActionAccess().getValueSignalParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Actuator returns Actuator
	 *
	 * Constraint:
	 *     {Actuator}
	 */
	protected void sequence_Actuator(ISerializationContext context, Actuator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Brick returns Actuator
	 *
	 * Constraint:
	 *     (name=EString pins+=EInt pins+=EInt*)
	 */
	protected void sequence_Actuator_Brick(ISerializationContext context, Actuator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     App returns App
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         initial=[State|EString] 
	 *         bricks+=Brick 
	 *         bricks+=Brick* 
	 *         states+=State 
	 *         states+=State*
	 *     )
	 */
	protected void sequence_App(ISerializationContext context, App semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Brick returns KeyboardSensor
	 *
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Brick_KeyboardSensor(ISerializationContext context, KeyboardSensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBrickAccess().getNameEStringParserRuleCall_2_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Brick returns LCDScreenActuator
	 *
	 * Constraint:
	 *     (name=EString pins+=EInt pins+=EInt*)
	 */
	protected void sequence_Brick_LCDScreenActuator(ISerializationContext context, LCDScreenActuator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Brick returns Sensor
	 *
	 * Constraint:
	 *     (name=EString pins+=EInt pins+=EInt*)
	 */
	protected void sequence_Brick_Sensor(ISerializationContext context, Sensor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Condition returns Condition
	 *
	 * Constraint:
	 *     (operator=Operator sensor=[Sensor|EString] signal=Signal)
	 */
	protected void sequence_Condition(ISerializationContext context, Condition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.CONDITION__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.CONDITION__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.CONDITION__SENSOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.CONDITION__SENSOR));
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.CONDITION__SIGNAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.CONDITION__SIGNAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConditionAccess().getOperatorOperatorEnumRuleCall_0_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getConditionAccess().getSensorSensorEStringParserRuleCall_1_0_1(), semanticObject.eGet(ArduinoMLPackage.Literals.CONDITION__SENSOR, false));
		feeder.accept(grammarAccess.getConditionAccess().getSignalSignalParserRuleCall_3_0(), semanticObject.getSignal());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Signal returns DigitalSignal
	 *     DigitalSignal returns DigitalSignal
	 *
	 * Constraint:
	 *     value=DigitalSignalEnum
	 */
	protected void sequence_DigitalSignal(ISerializationContext context, DigitalSignal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.DIGITAL_SIGNAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.DIGITAL_SIGNAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDigitalSignalAccess().getValueDigitalSignalEnumEnumRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     InitialCondition returns Condition
	 *
	 * Constraint:
	 *     (sensor=[Sensor|EString] signal=Signal)
	 */
	protected void sequence_InitialCondition(ISerializationContext context, Condition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.CONDITION__SENSOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.CONDITION__SENSOR));
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.CONDITION__SIGNAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.CONDITION__SIGNAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInitialConditionAccess().getSensorSensorEStringParserRuleCall_0_0_1(), semanticObject.eGet(ArduinoMLPackage.Literals.CONDITION__SENSOR, false));
		feeder.accept(grammarAccess.getInitialConditionAccess().getSignalSignalParserRuleCall_2_0(), semanticObject.getSignal());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     KeyboardSensor returns KeyboardSensor
	 *
	 * Constraint:
	 *     {KeyboardSensor}
	 */
	protected void sequence_KeyboardSensor(ISerializationContext context, KeyboardSensor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LCDScreenActuator returns LCDScreenActuator
	 *
	 * Constraint:
	 *     {LCDScreenActuator}
	 */
	protected void sequence_LCDScreenActuator(ISerializationContext context, LCDScreenActuator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Sensor returns Sensor
	 *
	 * Constraint:
	 *     {Sensor}
	 */
	protected void sequence_Sensor(ISerializationContext context, Sensor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     State returns State
	 *
	 * Constraint:
	 *     (name=EString actions+=Action actions+=Action* transition=Transition)
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Signal returns StringSignal
	 *     StringSignal returns StringSignal
	 *
	 * Constraint:
	 *     value=EString
	 */
	protected void sequence_StringSignal(ISerializationContext context, StringSignal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ArduinoMLPackage.Literals.STRING_SIGNAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ArduinoMLPackage.Literals.STRING_SIGNAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringSignalAccess().getValueEStringParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (conditions+=InitialCondition conditions+=Condition* next=[State|EString])
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
