/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.validation;

import fr.unice.polytech.si5.dsl.rhythm.validation.AbstractRhythmValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RhythmValidator extends AbstractRhythmValidator {
}
