/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.polytech.unice.borduino.concretesyntax.BorduinoRuntimeModule;
import com.polytech.unice.borduino.concretesyntax.BorduinoStandaloneSetup;
import com.polytech.unice.borduino.concretesyntax.ide.BorduinoIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BorduinoIdeSetup extends BorduinoStandaloneSetup {
  @Override
  public Injector createInjector() {
    BorduinoRuntimeModule _borduinoRuntimeModule = new BorduinoRuntimeModule();
    BorduinoIdeModule _borduinoIdeModule = new BorduinoIdeModule();
    return Guice.createInjector(Modules2.mixin(_borduinoRuntimeModule, _borduinoIdeModule));
  }
}
