/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.ide;

import com.polytech.unice.borduino.concretesyntax.ide.AbstractBorduinoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BorduinoIdeModule extends AbstractBorduinoIdeModule {
}
