/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RhythmStandaloneSetup extends RhythmStandaloneSetupGenerated {

	def static void doSetup() {
		new RhythmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
