/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.ui.contentassist;

import fr.unice.polytech.si5.dsl.rhythm.ui.contentassist.AbstractRhythmProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RhythmProposalProvider extends AbstractRhythmProposalProvider {
}
