/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.ui;

import com.polytech.unice.borduino.concretesyntax.ui.AbstractBorduinoUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BorduinoUiModule extends AbstractBorduinoUiModule {
  public BorduinoUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
