/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.validation;

import com.polytech.unice.borduino.concretesyntax.validation.AbstractBorduinoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BorduinoValidator extends AbstractBorduinoValidator {
}
