/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm;

import fr.unice.polytech.si5.dsl.rhythm.RhythmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RhythmStandaloneSetup extends RhythmStandaloneSetupGenerated {
  public static void doSetup() {
    new RhythmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
