/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm;

import fr.unice.polytech.si5.dsl.rhythm.AbstractRhythmRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RhythmRuntimeModule extends AbstractRhythmRuntimeModule {
}
