/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.ui.contentassist;

import com.polytech.unice.borduino.concretesyntax.ui.contentassist.AbstractBorduinoProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BorduinoProposalProvider extends AbstractBorduinoProposalProvider {
}
