/**
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.scoping;

import com.polytech.unice.borduino.concretesyntax.scoping.AbstractBorduinoScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BorduinoScopeProvider extends AbstractBorduinoScopeProvider {
}
