/*
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BorduinoRuntimeModule extends AbstractBorduinoRuntimeModule {
}
