/*
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBorduinoScopeProvider extends DelegatingScopeProvider {
}
