/*
 * generated by Xtext 2.14.0
 */
package com.polytech.unice.borduino.concretesyntax.parser.antlr;

import com.google.inject.Inject;
import com.polytech.unice.borduino.concretesyntax.parser.antlr.internal.InternalBorduinoParser;
import com.polytech.unice.borduino.concretesyntax.services.BorduinoGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BorduinoParser extends AbstractAntlrParser {

	@Inject
	private BorduinoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBorduinoParser createParser(XtextTokenStream stream) {
		return new InternalBorduinoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "App";
	}

	public BorduinoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BorduinoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
