/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.si5.dsl.rhythm.parser.antlr.internal.InternalRhythmParser;
import fr.unice.polytech.si5.dsl.rhythm.services.RhythmGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RhythmParser extends AbstractAntlrParser {

	@Inject
	private RhythmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRhythmParser createParser(XtextTokenStream stream) {
		return new InternalRhythmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Rhythm";
	}

	public RhythmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RhythmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
