/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.dsl.rhythm.scoping;

import fr.unice.polytech.si5.dsl.rhythm.scoping.AbstractRhythmScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RhythmScopeProvider extends AbstractRhythmScopeProvider {
}
